"""initial schema

Revision ID: 6248751bc321
Revises: 
Create Date: 2026-10-03 19:05:00.923467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '6248751bc321'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Render Postgres (and a fresh local pgvector/pgvector image) both need
    # this created before any vector column can exist.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('cik', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sector', sa.String(length=128), nullable=True),
    sa.Column('sic', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_cik'), 'companies', ['cik'], unique=False)
    op.create_index(op.f('ix_companies_ticker'), 'companies', ['ticker'], unique=True)
    op.create_table('taxonomy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('group', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taxonomy_slug'), 'taxonomy', ['slug'], unique=True)
    op.create_table('filings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('accession', sa.String(length=32), nullable=False),
    sa.Column('form_type', sa.String(length=16), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('filed_date', sa.Date(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('item1a_text', sa.Text(), nullable=True),
    sa.Column('item7_text', sa.Text(), nullable=True),
    sa.Column('item7a_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'accession', name='uq_filing_accession')
    )
    op.create_index(op.f('ix_filings_company_id'), 'filings', ['company_id'], unique=False)
    op.create_index(op.f('ix_filings_fiscal_year'), 'filings', ['fiscal_year'], unique=False)
    op.create_table('financial_facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('metric', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'fiscal_year', 'metric', name='uq_fact_metric_year')
    )
    op.create_index(op.f('ix_financial_facts_company_id'), 'financial_facts', ['company_id'], unique=False)
    op.create_index(op.f('ix_financial_facts_fiscal_year'), 'financial_facts', ['fiscal_year'], unique=False)
    op.create_table('news_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['taxonomy.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_news_items_company_id'), 'news_items', ['company_id'], unique=False)
    op.create_index(op.f('ix_news_items_published_at'), 'news_items', ['published_at'], unique=False)
    op.execute(
        "CREATE INDEX ix_news_items_embedding_hnsw ON news_items "
        "USING hnsw (embedding vector_cosine_ops)"
    )
    op.create_table('price_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('ann_vol', sa.Float(), nullable=True),
    sa.Column('beta', sa.Float(), nullable=True),
    sa.Column('dd95_1y', sa.Float(), nullable=True),
    sa.Column('mcap', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_stats_company_id'), 'price_stats', ['company_id'], unique=False)
    op.create_table('risks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filing_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('category_confidence', sa.Float(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('position_idx', sa.Integer(), nullable=False),
    sa.Column('merged_count', sa.Integer(), nullable=False),
    sa.Column('is_generic', sa.Boolean(), nullable=False),
    sa.Column('generic_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['taxonomy.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risks_company_id'), 'risks', ['company_id'], unique=False)
    op.create_index(op.f('ix_risks_filing_id'), 'risks', ['filing_id'], unique=False)
    op.create_table('tone_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filing_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('neg_ratio', sa.Float(), nullable=False),
    sa.Column('unc_ratio', sa.Float(), nullable=False),
    sa.Column('mean_position', sa.Float(), nullable=False),
    sa.Column('risk_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['taxonomy.id'], ),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tone_stats_filing_id'), 'tone_stats', ['filing_id'], unique=False)
    op.create_table('drift_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('from_filing_id', sa.Integer(), nullable=True),
    sa.Column('to_filing_id', sa.Integer(), nullable=False),
    sa.Column('risk_id', sa.Integer(), nullable=True),
    sa.Column('prev_risk_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=16), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['from_filing_id'], ['filings.id'], ),
    sa.ForeignKeyConstraint(['prev_risk_id'], ['risks.id'], ),
    sa.ForeignKeyConstraint(['risk_id'], ['risks.id'], ),
    sa.ForeignKeyConstraint(['to_filing_id'], ['filings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drift_events_company_id'), 'drift_events', ['company_id'], unique=False)
    op.create_table('mc_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('risk_id', sa.Integer(), nullable=False),
    sa.Column('params_json', sa.JSON(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('n_sims', sa.Integer(), nullable=False),
    sa.Column('mean', sa.Float(), nullable=False),
    sa.Column('median', sa.Float(), nullable=False),
    sa.Column('var95', sa.Float(), nullable=False),
    sa.Column('var99', sa.Float(), nullable=False),
    sa.Column('cvar95', sa.Float(), nullable=False),
    sa.Column('cvar99', sa.Float(), nullable=False),
    sa.Column('hist_bins_json', sa.JSON(), nullable=False),
    sa.Column('exceed_json', sa.JSON(), nullable=False),
    sa.Column('mitigation_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['risk_id'], ['risks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mc_runs_risk_id'), 'mc_runs', ['risk_id'], unique=False)
    op.create_table('news_risk_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('risk_id', sa.Integer(), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['news_items.id'], ),
    sa.ForeignKeyConstraint(['risk_id'], ['risks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_risk_links_news_id'), 'news_risk_links', ['news_id'], unique=False)
    op.create_index(op.f('ix_news_risk_links_risk_id'), 'news_risk_links', ['risk_id'], unique=False)
    op.create_table('risk_embeddings',
    sa.Column('risk_id', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.ForeignKeyConstraint(['risk_id'], ['risks.id'], ),
    sa.PrimaryKeyConstraint('risk_id')
    )
    op.execute(
        "CREATE INDEX ix_risk_embeddings_embedding_hnsw ON risk_embeddings "
        "USING hnsw (embedding vector_cosine_ops)"
    )
    op.create_table('risk_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('risk_id', sa.Integer(), nullable=False),
    sa.Column('p_mean', sa.Float(), nullable=False),
    sa.Column('p_lo', sa.Float(), nullable=False),
    sa.Column('p_hi', sa.Float(), nullable=False),
    sa.Column('alpha', sa.Float(), nullable=False),
    sa.Column('beta', sa.Float(), nullable=False),
    sa.Column('impact_usd', sa.Float(), nullable=False),
    sa.Column('impact_pct_ebitda', sa.Float(), nullable=False),
    sa.Column('impact_norm', sa.Float(), nullable=False),
    sa.Column('impact_band', sa.Integer(), nullable=False),
    sa.Column('expected_loss', sa.Float(), nullable=False),
    sa.Column('zone', sa.String(length=16), nullable=False),
    sa.Column('inputs_json', sa.JSON(), nullable=False),
    sa.Column('fallbacks', sa.JSON(), nullable=False),
    sa.Column('scored_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['risk_id'], ['risks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_scores_risk_id'), 'risk_scores', ['risk_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_scores_risk_id'), table_name='risk_scores')
    op.drop_table('risk_scores')
    op.drop_table('risk_embeddings')
    op.drop_index(op.f('ix_news_risk_links_risk_id'), table_name='news_risk_links')
    op.drop_index(op.f('ix_news_risk_links_news_id'), table_name='news_risk_links')
    op.drop_table('news_risk_links')
    op.drop_index(op.f('ix_mc_runs_risk_id'), table_name='mc_runs')
    op.drop_table('mc_runs')
    op.drop_index(op.f('ix_drift_events_company_id'), table_name='drift_events')
    op.drop_table('drift_events')
    op.drop_index(op.f('ix_tone_stats_filing_id'), table_name='tone_stats')
    op.drop_table('tone_stats')
    op.drop_index(op.f('ix_risks_filing_id'), table_name='risks')
    op.drop_index(op.f('ix_risks_company_id'), table_name='risks')
    op.drop_table('risks')
    op.drop_index(op.f('ix_price_stats_company_id'), table_name='price_stats')
    op.drop_table('price_stats')
    op.drop_index(op.f('ix_news_items_published_at'), table_name='news_items')
    op.drop_index(op.f('ix_news_items_company_id'), table_name='news_items')
    op.drop_table('news_items')
    op.drop_index(op.f('ix_financial_facts_fiscal_year'), table_name='financial_facts')
    op.drop_index(op.f('ix_financial_facts_company_id'), table_name='financial_facts')
    op.drop_table('financial_facts')
    op.drop_index(op.f('ix_filings_fiscal_year'), table_name='filings')
    op.drop_index(op.f('ix_filings_company_id'), table_name='filings')
    op.drop_table('filings')
    op.drop_index(op.f('ix_taxonomy_slug'), table_name='taxonomy')
    op.drop_table('taxonomy')
    op.drop_index(op.f('ix_companies_ticker'), table_name='companies')
    op.drop_index(op.f('ix_companies_cik'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
